### ISSUE TITLE
Bg image inside Find a Joomla! Extension section is  not perfect in responsive layout

### ISSUE THREAD

**Issue by arunsasi** [dneukirchen/joomla-org-template#13]
![bg-image](https://cloud.githubusercontent.com/assets/270789/16945381/5e78d1f0-4dc2-11e6-9e8d-04aaace33869.png)

**Comment by dneukirchen** [comment]
Any suggestions?

**Comment by arunsasi** [comment]
Update the css in media query

`.section-3 {
    padding: 65px 0 65px;
}`
