### ISSUE TITLE
Add TM to Brandmark

### ISSUE THREAD

**Issue by coolcat-creations** [dneukirchen/joomla-org-template#22]
Joomla Brandmark inside the magnifier the TM is missing (important)

**Comment by dneukirchen** [comment]
:(

**Comment by aDaneInSpain** [comment]
Should not be difficult to add? Maybe @designbengel could do it?

**Comment by coolcat-creations** [comment]
isn´t difficult but i have lots of j 3.6 imagery to do on my list. So i´d prefer if someone of the redesign team can apply it into the graphic. thanks!

**Comment by dneukirchen** [comment]
graphic is located here: https://github.com/dneukirchen/joomla-org-template/blob/master/src/demo/img/finder-bg.jpg

**Comment by aDaneInSpain** [comment]
OK, will do it.

**Comment by aDaneInSpain** [comment]
@designbengel Is there any rule for where the TM should be? I assume top right of the logo?

**Comment by coolcat-creations** [comment]
https://tm.joomla.org/brand-manual-and-limited-use-logos ;-)

**Comment by aDaneInSpain** [comment]
Yeah, sorry. Was being lazy sorry :-/ 

I have updated the image. Pull request incoming.
