### ISSUE TITLE
All links in the footer are yet not linked to content

### ISSUE THREAD

**Issue by coolcat-creations** [dneukirchen/joomla-org-template#24]

**Comment by arunsasi** [comment]
**Get Information**
**About Joomla!** https://www.joomla.org/about-joomla.html
**Features** https://www.joomla.org/core-features.html
**Joomla! Magazine** http://magazine.joomla.org/
**Announcement**s https://www.joomla.org/announcements.html
**Shop** https://shop.joomla.org/
**Contact** https://www.joomla.org/media-contact.html

**Comment by arunsasi** [comment]
**Community Forum** is repeating in two section **Get Started** and **Get Involved**. Need to check which one need to remove form footer menu

**Comment by arunsasi** [comment]
Footer navigation links updated. PFA.
@designbengel  @BrittaStender @aDaneInSpain  Please cross check the links.
[footer-navigation.zip](https://github.com/dneukirchen/joomla-org-template/files/386812/footer-navigation.zip)
